# fly.toml app configuration file generated for amis-api on 2026-07-13T00:39:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "amis-api"
primary_region = "dfw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  processes = ['app']
